### ISSUE TITLE
nbviewer.jupyter.org and downstream mybinder.org don't update from github repo changes

### ISSUE THREAD

**Issue by arminus** [arminus/osm-schutzgebiete#1]
See also https://discourse.jupyter.org/t/updating-binder-from-changes-on-github/7731/2

Most likely caused by this https://github.com/jupyter/nbviewer/issues/914

**Comment by bryevdv** [comment]
Seems highly unlikely that they are related. nbviewer runs nbexport to cache static (not live at all) HTML renders of notebooks. Binder, which is run by entirely different people and shares no infrastructure at all with nbviewer, is an orchestration service that runs live notebooks on a cloud backend.

**Comment by arminus** [comment]
Understood.
